version: '3.1'

services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - '3306:3306'
    volumes:
      - '/home/prkwan/development/mysql:/var/lib/mysql'
